version: "3.4"

services:

  client-mysql:
    image: "mysql:5.7.24"
    container_name: client-mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "client"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pass"
    volumes:
      - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"

  client-jaeger:
    image: jaegertracing/all-in-one:1.22.0
    container_name: client-jaeger
    ports:
      - "14268:14268"   # jaeger-collector HTTP server (tracer provider)
      - "16686:16686"   # HTTP server (browser UI)